language: node_js
node_js:
  - 14
cache:
  directories:
    - node_modules
install:
  - echo 'Installing Dependecies...'
  - npm install
script:
  - echo 'Formatting Code...'
  - npm run lint
  - echo 'Testing...'
  - npm run test:coverage
after_script: npm run coveralls